
---
services:
  # Combined frontend and backend service
  # dms:
    # <your dms container stuff>
    # ...
  
  dms-gui:
    # logging:
      # driver: journald
      # options:
        # tag: dms

    build:                                              # comment me for official image
      context: .                                        # comment me for official image
      # build: any ARG in Dockerfile must be there too; cannot use environment variables here
      args:
        - ENV_MODE=production
        - UPSTREAM_NGINX=try_files $$uri $$uri/ /index.html;
      #   - ENV_MODE=development                          # comment me for production
      #   - UPSTREAM_NGINX=proxy_pass ${FRONTEND_PROXY_URL}; proxy_http_version 1.1; proxy_set_header Upgrade $$http_upgrade; proxy_set_header Connection "upgrade";  # comment me for production
    image: audioscavenger/dms-gui:latest
    container_name: dms-gui
    hostname: dms-gui
    restart: unless-stopped
    
    expose:
      - 80      # frontend via internal nginx
      - 3001    # frontend: webpack-dev-server if you can get it to run inside the container... good luck
      - 3000    # backend and docs
      
    env_file: ./config/dms-gui/.dms-gui.env
    environment:
      - TZ=${TZ:-UTC}
      - isDEMO=${isDEMO:-false}                         # DEMO mode
      - DATABASE_RESET=${DATABASE_RESET:-false}         # to reset the database each time; used for DEMO
      - DEBUG=${DEBUG:-true}                            # enable debugging
      # - ENV_MODE=development                          # comment me for production

    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./config/dms-gui/:/app/config/

      # If you want to develop locally... mount the backend with DEBUG=true and nodemon will reload your stuff immediately
      # - ./backend:/app/backend
      ## The below does not work anymore, use nvm-sh to build a local nodeJS of the same version as the container:
      # - ./frontend.mjs/package.json:/app/frontend/package.json
      # - ./frontend.mjs/package-lock.json:/app/frontend/package-lock.json
      ## frontend upgrade commands: from the OS; do that once
      #   curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.4/install.sh | bash
      #   source ~/.bashrc
      #   nvm install 24.9.0
      
    # add your proxy network if you need:
    networks:
      frontend:

networks:
  frontend:
    external: true
    name: frontend
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-frontend
