# https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax
# https://github.com/peter-evans/dockerhub-description

name: Update Docker Hub Description

on: release
# on:
  # push:
    # branches:
      # - main
    # paths:
      # - 'README.dockerhub.md'

jobs:
  update-dockerhub-description:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Update Docker Hub Description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: audioscavenger/dms-gui
          readme-filepath: ./README.dockerhub.md
          short-description: ${{ github.event.repository.description }}
          enable-url-completion: true


